#thymeleaf
spring:
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    cache: false
    servlet:
      content-type: text/html
#durid
  datasource:
      url: jdbc:mysql://127.0.0.1:3306/seckill
      username: root
      password: 123
      # 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
#redis
  redis:
    host: localhost
    port: 6379
    password:
    timeout: 10000 #客户端超时时间单位是毫秒 默认是2000
    jedis:
      pool:
        max-idle: 8 # 连接池中的最大空闲连接
        max-active: 200 #连接池最大连接数
        max-wait: -1  #连接池最大阻塞时间（负数表示没有限制）
        min-idle: 0
#mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.ly.seckill.domain
  configuration:
    map-underscore-to-camel-case: true  #下划线转驼峰
logging:
  level:
    com.ly.seckill.mapper:  debug

